// API
interface PQ_adjusters {
  adid: number;
  adgid: number;
  adname: string;
  ademail: string;
  adphone: string;
  adagency: string;
  adtype: string;
  adactive: string;
  adkey: string;
}

interface PQ_adjustersAgency {
  agid: number;
  agname: string;
  agview: string;
}

interface PQ_building {
  bid: number;
  badate: any;
  bedate: any;
  blid: number;
  bcid: number;
  bmid: number;
  bcontact: string;
  bcontactphone: any;
  btype: string;
  bsector: string;
  bsize: number;
  bfloors: number;
  blayers: number;
  bpitch: any;
  broof: string;
  broofmat: string;
  bmaterial: string;
  bmaterial2: string;
  bmaterial3: string;
  bhatch: string;
  bheight: number;
  bbheight: number;
  bsys: string;
  bmfr: number;
  bmil: string;
  bwar: string;
  binstall: any;
  blastserv: any;
  bnextserv: any;
  blastrep: any;
  bnextrep: any;
  bname: string;
  bnum: string;
  bsame: string;
  baddr1: string;
  baddr2: string;
  bcity: string;
  bst: string;
  bzip: number;
  blatlon: string;
  bnotes: string;
  bcnt: string;
  bcntemail: string;
  bcntphone: any;
  bview: string;
  caid: number;
  caname: string;
  shinglecostbundle: any;
  underlaymentcostbundle: any;
  icewatercost: any;
  hipridgecost: any;
  startershinglecost: any;
  nailcost: any;
  staplecost: any;
  ventingcost: any;
  caactive: string;
  cid: number;
  cuid: number;
  ctype: string;
  clientstatus: string;
  clientsubstatus: string;
  cismgmt: string;
  ccomp: string;
  caddr1: string;
  caddr2: string;
  ccity: string;
  cst: string;
  czip: number;
  cext: string;
  ccontact: string;
  ctitle: string;
  cemail: string;
  cemailAlt: string;
  cemailAlt2: string;
  cemailAlt3: string;
  cemailAlt4: string;
  cemailAlt5: string;
  cemailAlt6: string;
  ccontact2: string;
  ctitle2: string;
  cphone2: any;
  cext2: string;
  cemail2: string;
  cemail2cc: string;
  cemailbilling: string;
  caltemailbilling: string;
  curl: string;
  cnotes: string;
  cpayterms: string;
  cview: string;
  csalesid: number;
  creferral: string;
  cqbid: number;
  cqbresp: string;
  clatefee: any;
  cwaivelate: string;
  clotid: number;
  cinid: number;
  capp: any;
  cinvpays: string;
  cstatus2: string;
  cstatusuid: number;
  cstatusreason: string;
  cstatusdate: any;
  clatlon: string;
  cnnote: string;
  cinspection: any;
  clastcontact: any;
  clastcontactuid: number;
  cncid: any;
  cnuid: any;
  cndate: any;
  cnid: any;
  Id: number;
  company: string;
  fullname: string;
  matched: string;
  csid: number;
  cscid: number;
  csuid: number;
  cskey: string;
  csdtsemail: any;
  csdtsview: any;
  coid: number;
  coapplyto: string;
  coname: string;
  colicense1: string;
  colicense2: string;
  colicense3: string;
  colicense4: string;
  coaddr1: string;
  coaddr2: string;
  cocity: string;
  costate: string;
  cozip: string;
  cophone1: string;
  cophone2: string;
  coemail: string;
  cofax: string;
  courl: string;
  cstatusmaster: string;
  cservices: string;
  csector: string;
  coins: string;
  comatloc: number;
  colatlon: string;
  cologo: string;
  coresdue: number;
  cocomdue: number;
  colaterate: any;
  coinnotecom: string;
  coinnoteres: string;
  cointerms: string;
  coincontingency: string;
  coeula: string;
  coeulaversion: any;
  cocctoken: string;
  coreviewlink: string;
  coreviewtext: string;
  coexpdaysres: number;
  coexpdayscom: number;
  cotimezone: string;
  cocheckout: string;
}

interface PQ_coms {
  comid: number;
  comlid: number;
  comsalesid: number;
  comdts: any;
  comkey: string;
  comurl: string;
  comshow: string;
  cntid: number;
  cntclientid: number;
  cntname: string;
  cnttitle: string;
  cntemail: string;
  cntphone: any;
  cntview: string;
  ctid: number;
  ctlid: number;
  ctcid: number;
  ctinid: number;
  ctjid: number;
  ctstatus: any;
  ctdts: any;
  ctname: string;
  ctip: string;
  ctipxfrom: string;
  ctlatlon: string;
  ctua: string;
  crid: number;
  cruid: number;
  crwotype: string;
  crdata: string;
  crmid: any;
  crmname: string;
  crmaddr1: string;
  crmaddr2: string;
  crmcity: string;
  crmstate: string;
  crmzip: string;
  crmemail: string;
  crmphone: string;
  crmphonealt: string;
  crmweb: string;
  crmactive: string;
  crmtags: string;
  crmcat: string;
  crmncrmid: any;
  crmnname: string;
  crmnemail: string;
  crmnphone: string;
  crmnid: any;
  dfid: number;
  dfcat: string;
  dfname: string;
  dfdesc: string;
  dfcorrect: string;
  dfunit: string;
  dfcost: any;
  eid: number;
  elabel: string;
  erecip: string;
}

interface PQ_eula {
  eulaid: any;
  eulaver: any;
  eulatext: string;
  euladts: any;
}

interface PQ_eulaSig {
  eulasid: number;
  eulasuid: any;
  eulasversion: any;
  eulassig: string;
  eulasdts: any;
  eid: number;
  euid: number;
  ejid: number;
  ecid: number;
  elid: number;
  elocid: number;
  etype: string;
  estartdts: any;
  eenddts: any;
  eallday: string;
  etitle: string;
  edesc: string;
  estatus: string;
  eauid: number;
  eadts: any;
  eduration: number;
  edurationtyp: string;
  notify_emails: string;
  notify_names: string;
  id: number;
  sometext: string;
  number: any;
  phone: any;
  mydate: any;
  optionvalue: string;
  email: string;
  checkboxes: string;
  somemoretext: string;
  radios: string;
  hrsjid: number;
  hrsuid: number;
  inid: number;
  inlid: number;
  inbid: number;
  incid: number;
  injid: number;
  inlotid: number;
  indts: any;
  incomsalesid: number;
  incomdts: any;
  incomkey: string;
  incomshow: string;
  insimpleinspections: string;
  inservices: string;
  inprojectidcc: any;
  inurlappcc: string;
  inurlpubcc: string;
  inurlprojcc: string;
  jrpiid: number;
  jrpijrid: number;
  jrpiorder: number;
  jrpifilename: string;
  icjid: number;
  icaid: number;
  icadid: number;
  icuid: number;
  icstatus: string;
  icdts: any;
  iclossdts: any;
  icdiscdts: any;
  icadjsched: any;
  icclaimnum: string;
  icpolicynum: string;
  icinsuranceco: string;
  icamount: any;
  icamountdts: any;
  icamountworking: any;
  icsimpleinspections: string;
  icadjatt: any;
  iccovsumrec: any;
  icinsupsub: any;
  icsufcovapp: any;
  icprojectidcc: any;
  icurlappcc: string;
  irurlpubcc: string;
  icid: number;
  icclause: string;
}

interface PQ_insuranceCo {
  inid: number;
  inname: string;
  inphone: string;
  inemail: string;
  inactive: string;
}

interface PQ_insuranceContacts {
  incid: number;
  incinid: number;
  inctype: string;
  incname: string;
  incphone: string;
  incemail: string;
  incactive: string;
  ihid: number;
  ihjid: number;
  ihwoid: number;
  ihwotype: string;
  ihuid: number;
  ihdts: any;
  ihresponsedts: any;
  ihpayload: string;
  ihresponse: string;
  invid: number;
  invcid: number;
  invjid: number;
  invjrid: number;
  invuid: number;
  invdate: any;
  invdatedue: any;
  invsent: any;
  invopen: any;
  invaccept: any;
  invstatus: string;
  invtype: string;
  invtotal: any;
  invkey: string;
  invreason: string;
  invcommuid: number;
  invcommtot: any;
  invcommdts: any;
  invcommtot2: any;
  invcommdts2: any;
  iqbid: number;
  iqbstat: number;
  iqbinvoicenum: string;
  iqbresp: string;
  iqbitem: string;
  invnolate: any;
  invpaidfull: any;
  invlatefee: any;
  invpaid: any;
  invpays: string;
  invpaysid: string;
  invpaystatus: string;
  invtm: any;
  inid: number;
  innote: string;
}

interface PQ_invoicePayments {
  ipid: number;
  ipcid: number;
  ipjid: number;
  ipjrid: number;
  ipuid: number;
  ipdate: any;
  ipamt: any;
  ipfee: any;
  iptype: string;
  ipmeth: string;
  ipchknum: string;
  ipqbid: string;
  ipqbresp: string;
  ipccpayload: string;
  ipccresponse: string;
  ipdid: number;
  ipdinvid: number;
  ipddts: any;
  ipdpayload: string;
  ipdresult: string;
  jid: number;
  jpmgr: number;
  jadate: any;
  jstatus: string;
  qstatus: string;
  jsched: any;
  jtype: string;
  jsector: string;
  jwork: string;
  jprefdate: any;
  jodeldts: any;
  jodumpsterco: string;
  jodumpsterdate: any;
  jopermit: any;
  joinspection: any;
  jinstaller: number;
  jinstallon: any;
  jinstalldate: any;
  jinstalldesc: string;
  jinsurance: string;
  jinsuranceco: string;
  jinsuranceadj: string;
  jinsuranceadjphone: any;
  jinsuranceadjemail: string;
  jorigcoverage: any;
  jclaimnum: string;
  jwarranty: string;
  jservice: string;
  jnotes: string;
  jreason: string;
  jreasonuid: number;
  jreasondts: any;
  jlink: number;
  jcopiedfrom: number;
  jmailed: number;
  jstarted: any;
  jfinished: any;
  jeta: any;
  jsubmitted: any;
  jkey: string;
  jrate: string;
  jratenotes: string;
  jcontact: string;
  jcontactphone: any;
  jwoct: number;
  jlotid: number;
  jqnotes: string;
  jcid: any;
  jlid: any;
  jbid: any;
  juid: any;
  jauid: any;
  jouid: any;
  jpublicadj: any;
  jcontid: any;
  jcostid: number;
  jcjid: number;
  jcjrid: number;
  jcuid: number;
  jcdts: any;
  jcmatordered: any;
  jcshopmat: any;
  jcdisposal: any;
  jcmiscmater: any;
  jcpermit: any;
  jceagleview: any;
  jcsublabor: any;
  jcexpense: any;
  jcextras: any;
  jctotalcost: any;
  jcreturns: any;
  jcmarketing: any;
  jcleadfee: any;
  jcfinalcost: any;
  jcnotes: string;
  jcmisc: any;
  jcdone: any;
  jcwarrcost: any;
  jccommpayout: any;
  jhid: number;
  jhjid: number;
  jhuid: number;
  jhwoid: number;
  jhhours: any;
  jhdate: any;
  jhstart: any;
  jhend: any;
  jhuser: string;
  jhrate: any;
  jhdts: any;
  jhcb: any;
  jnid: number;
  jnjid: number;
  jnwoid: number;
  jnuid: number;
  jndts: any;
  jnbody: string;
  psid: number;
  pstype: string;
  psmarket: string;
  pscat: string;
  pstitle: string;
  psdesc: string;
  psqty: any;
  psqtytype: string;
  pstemplate: string;
  pscost: any;
  psview: string;
  mid: number;
  mfr: string;
  maddr1: string;
  mcity: string;
  mstate: string;
  mzip: number;
  mphone: any;
  memail: string;
}

interface PQ_jobOrderPhotos {
  jrpid: number;
  jrpjrid: number;
  jrpwoid: number;
  jrptype: string;
  jrporder: number;
  jrplabel: string;
  jrpdetail: string;
  jrpstyle: string;
  jrpcolor: string;
  jrpmfr: string;
  jrpfilename: string;
  jrpunits: number;
  jrpunittype: string;
  jrpunitcost: any;
  jrpcost: any;
  jrppub: string;
  jrpdisp: string;
  jrpinst: number;
  jrpttype: string;
  jrid: number;
  jrjid: number;
  jrtype: string;
  jruid: number;
  jrdate: any;
  jrexpire: any;
  jrinsclause: string;
  jrwarr: number;
  jrwarr2: number;
  jrnote: string;
  jrterms: string;
  jrtotalcost: any;
  jrdepreq: any;
  jronote: string;
  jroedts: any;
  jrqty: string;
  jriid: number;
  jrijrid: number;
  jritem: string;
  jricost: any;
  jrpmapparams: string;
  jrpmapcenter: string;
  jrpgrade: string;
  jrppubcost: string;
  jrpcopy: number;
  jrpusequotefile: any;
  jrpuseclaimfile: any;
  jrpusewofile: number;
  jrpdate: any;
  jrpphotoidcc: any;
  jrpphotodtscc: any;
  jrpdts: any;
  jtid: number;
  jtjid: number;
  jtuid: number;
  jtname: string;
  jtdate: any;
  jtshare: string;
}

interface PQ_knowledgebase {
  id: number;
  title: string;
  article: string;
  cat: string;
  sticky: any;
  imgurl: string;
  vidurl: string;
  custonly: string;
  custexclude: string;
}

interface PQ_leadPhotos {
  lpid: number;
  lplid: any;
  lpcid: any;
  lpinid: any;
  lpfilename: string;
  lpext: string;
  lpcat: string;
  lpdts: any;
  lpphotoidcc: any;
  lpphotodtscc: any;
  lid: number;
  luid: number;
  lcid: number;
  ladate: any;
  lstatus: string;
  lstatus2: string;
  ltype: string;
  lservice: string;
  lstatusuid: number;
  lstatusreason: string;
  lstatusdate: any;
  llastcontact: any;
  llastcontactuid: number;
  lsource: string;
  lcomp: string;
  lcontact: string;
  ltitle: string;
  llname: string;
  laddr1: string;
  laddr2: string;
  lcity: string;
  lst: string;
  lzip: number;
  llatlon: string;
  lphone: string;
  lext: string;
  laltphone: string;
  laltext: string;
  lemail: string;
  llotid: any;
  lnotes: string;
  lfax: string;
  lcontact2: string;
  ltitle2: string;
  lphone2: any;
  lext2: string;
  lemail2: string;
  lemail2cc: string;
  lbtype: string;
  lbfloors: number;
  lbroofmat: string;
  lbhatch: string;
  lbheight: number;
  linspection: any;
  linspectioncomp: any;
  linspectionnotes: string;
  llocnotes: string;
  lapp: any;
  linvpays: string;
  linsuranceco: string;
  lclaimnum: string;
  lsimpleinspections: string;
  lnid: any;
  lnlid: any;
  lncid: any;
  lnuid: any;
  lncat: string;
  lndate: any;
  lnfollowup: any;
  lnfollowedup: any;
  lnnote: string;
  ledate: any;
  lclient: number;
  lname: string;
  lcounty: string;
  lview: string;
  logid: number;
  logcat: string;
  logtitle: string;
  loguid: number;
  logdts: any;
  logdataid: number;
  logaltdataid: number;
  lognote: string;
  ldts: any;
  luname: string;
  lremote_addr: string;
  lforward_for: string;
  lotid: number;
  lotname: string;
  lotaddress1: string;
  lotaddress2: string;
  lotcity: string;
  lotstate: any;
  lotzip: string;
  lotphone: any;
  lotemail: string;
  lotlogo: string;
  lothdr: string;
  lotview: string;
  lotcctoken: string;
}

/**
 * Represents the interface for PQ_masterAccounts.
 */
interface PQ_masterAccounts {
  maid: number;
  maco: string;
  maname: string;
  maaddr1: string;
  maaddr2: string;
  macity: string;
  mastate: string;
  mazip: string;
  maphone: string;
  madenyaccess: string;
  mid: number;
  mtype: string;
  mmarket: string;
  mcat: string;
  mtitle: string;
  mdesc: string;
  mqty: any;
  mqtytype: string;
  mtemplate: string;
  mcost: any;
  mservice: string;
  mview: string;
  miid: number;
  miorder: number;
  mimid: number;
  mimfr: string;
  mistyle: string;
  micolor: string;
  micost: any;
  mionhand: number;
  mihide: any;
  misys: any;
  mlid: any;
  mlcoid: number;
  mljid: any;
  mlwoid: number;
  mlwo: string;
  mlsid: number;
  mlsgid: number;
  mlitemorder: number;
  mlstatus: string;
  mlstatusreason: string;
  mlordertype: string;
  mlcreator: string;
  mlcreatorid: number;
  mlcreated: any;
  mlorder: string;
  mlorderid: number;
  mlordered: any;
  mlcancel: string;
  mlcancelid: number;
  mlcancelled: any;
  mldroploc: string;
  mldropwhid: number;
  mldropeta: any;
  mlreceive: string;
  mlreceived: any;
  mlproduction: any;
  mlrstatus: string;
  mlrnotes: string;
  mlrproblem: string;
  mlcalltosched: string;
  mlrpic: number;
  mlassign: string;
  mlassigndts: any;
  mlassignid: number;
  mlassignby: string;
  mlassignbyid: number;
  mlfix: string;
  mlfixid: number;
  mlfixed: any;
  mlnotes: string;
  mlintnotes: string;
  mlorderdelivfee: any;
  mlordertot: any;
  mlcredit: any;
  mlkey: string;
  mlacl: string;
  mlseen: any;
  mlseencancel: any;
  mlid2: string;
  mlfid: number;
  mlfmlid: number;
  mlfuid: number;
  mlfname: string;
  mliid: any;
  mlimlid: any;
  mlimid: number;
  mlimiid: number;
  mliordered: number;
  mlipulled: number;
  mlireceived: number;
  mlicost: any;
  mlireturned: number;
  mliopt: string;
  mlpicid: any;
  mlpicmlid: any;
  mlpicfilename: string;
  mlpicext: string;
  mlpicdts: any;
  mlpo: string;
  mltid: number;
  mltntid: number;
  mltsid: number;
  mltname: string;
  mlttype: string;
  mltmap: string;
  mltmarket: string;
  mltservice: string;
  mltnotes: string;
  mltorder: number;
  mltview: string;
  mltiid: number;
  mltimltid: number;
  mltimid: number;
  mlticalcvarid: number;
  mltimap: string;
  mltcoverage: string;
  psid: number;
  pstype: string;
  psmarket: string;
  pscat: string;
  pstitle: string;
  psdesc: string;
  psqty: any;
  psqtytype: string;
  pstemplate: string;
  pscost: any;
  psview: string;
  pqtid: number;
  pqttype: string;
  pqttemplate: string;
  pqtpsid: number;
  pqtorder: number;
  qid: number;
  qcid: number;
  qjid: number;
  qjrid: number;
  quid: number;
  qdate: any;
  qsent: any;
  qopen: any;
  qaccept: any;
  qstatus: string;
  qtype: string;
  qtotal: any;
  qkey: string;
  qreason: string;
  qcommuid: number;
  qcommtot: any;
  qcommdts: any;
  qcommtot2: any;
  qcommdts2: any;
  qqbid: number;
  qqbstat: number;
  qqbqoicenum: string;
  qqbresp: string;
  qqbitem: string;
  qcjid: number;
  qccosts: number;
  qcmarkup: number;
  qcdata: string;
  wsdid: number;
  wsdwsid: number;
  wsdjid: number;
  wsdlid: number;
  wsdjservice: string;
  wsdlservice: string;
  wsdform: string;
  wsdnotes: string;
  ruid: number;
  rurid: number;
  ruuid: number;
  rid: number;
  rname: string;
  rdesc: string;
  raccess: string;
  rdealer: string;
  rstatus: string;
  rcat: string;
  rfilephp: string;
  raid: number;
  raname: string;
  rafile: string;
  raactive: string;
  rarecipients: string;
  rdpid: number;
  rdprole: string;
  rdpgojs: string;
  ssid: number;
  ssuid: number;
  ssmonth: number;
  ssyear: number;
  sstotal: number;
  ssgoal: number;
  sjid: number;
  sdts: any;
  sname: string;
  sip: string;
  sipxfrom: string;
  slatlon: string;
  sua: string;
  internal: number;
  smsid: number;
  smsname: string;
  smsmsg: string;
  smsplacement: string;
  smsactive: string;
  sid: number;
  source: string;
  suid: number;
  suicid: number;
  suuid: number;
  suamountreq: any;
  suamountapp: any;
  sustatus: string;
  sudatereq: any;
  sudate: any;
  sunotes: string;
  sugid: number;
  suname: string;
  suaddress1: string;
  suaddress2: string;
  sucity: string;
  sustate: string;
  suzip: string;
  sucontact: string;
  suphone: any;
  suemail: string;
  sualtemail: string;
  suadded: any;
  suactive: string;
  suaccnum: string;
  suinventory: string;
  sulatlon: string;
  sudelivfee: any;
  susalestax: any;
  gid: number;
  gname: string;
  gcode: string;
  gnotes: string;
  gview: string;
  gsalesrep: string;
  gsalesrepphone: string;
  gsalesrepemail: string;
  gconpricing: string;
  gconexp: any;
  gaccnum: string;
  ginventory: string;
  tnid: any;
  tntid: any;
  tnuid: any;
  tndate: any;
  tnnote: string;
  tid: number;
  tjid: number;
  twoid: string;
  tuid: number;
  tassuid: number;
  ticid: number;
  tdts: any;
  tdeadlinedts: any;
  tdeadlinetime: any;
  topeneddts: any;
  tcompdts: any;
  tcat: string;
  tstatus: string;
  tpriority: string;
  tsummary: string;
  tdetails: string;
  treason: string;
  tname: string;
  ttext: string;
  ttype: number;
  tview: string;
  jrtid: number;
  jrtjid: number;
  jrtdts: any;
  jrtcategory: string;
  jrtorder: number;
  jrtlabel: string;
  jrtdetail: string;
  jrtfilename: string;
  jrtinstaller: string;
  uid: number;
  ulogin: string;
  upass: string;
  ufirstn: string;
  ulastn: string;
  uemail: string;
  uphone: any;
  uphonemobile: any;
  uadddts: any;
  uaddid: number;
  ueditdts: any;
  ueditid: number;
  ulastlogin: any;
  ulastdts: any;
  ulastpassdts: any;
  urole: string;
  uestimate: string;
  uclients: string;
  ujobs: string;
  uinstaller: string;
  utemplates: string;
  usuper: string;
  ustatus: string;
  uexpire: number;
  utitl: string;
  usys: string;
  ulock: string;
  umenuoverride: string;
  ucid: number;
  uaddpart: string;
  uaddpartrate: string;
  udefLot: string;
  ucntE: string;
  ucolor: string;
  ukey: string;
  uperms: string;
  ustart: string;
  ustartmobile: string;
  ufieldRe: string;
  uroles: string;
  urolesBKUP: string;
  uassign: string;
  uwidgets: string;
  urate: any;
  ulang: string;
  uintegrationcc: string;
  ucompanies: string;
  uservices: string;
  usalesgoal: number;
  usalesgoaly: any;
  ustagingaccess: any;
  umasteraccess: any;
  whid: number;
  whname: string;
  whaddress1: string;
  whaddress2: string;
  whcity: string;
  whstate: string;
  whzip: string;
  whcontact: string;
  whphone: any;
  whemail: string;
  whuid: number;
  whadded: any;
  whactive: string;
  whnotes: string;
  whiid: number;
  whiwhid: number;
  whimid: number;
  whimiid: number;
  whionhand: number;
  whicost: any;
  wid: number;
  wtitle: any;
  wlterm: number;
  wmterm: number;
  wdesc: string;
  wview: string;
  chid: number;
  chjid: number;
  chwoid: number;
  chuid: number;
  chdate: any;
  chdatein: any;
  chdateout: any;
  chcrewuids: string;
  wojid: number;
  wonotes: string;
  wostatus: string;
  PQ_woRoof: any;
}

interface PQ_materialsIDX {
  miid: number;
  miorder: number;
  mimid: number;
  mimfr: string;
  mistyle: string;
  micolor: string;
  micost: number;
  mionhand: number;
  mihide: number;
  misys: number;
  PQ_materialsIDX: any;
}

interface PQ_materialsList {
  mlid: number;
  mlcoid: number;
  mljid: number;
  mlwoid: number;
  mlwo: string;
  mlsid: number;
  mlsgid: number;
  mlitemorder: number;
  mlstatus: string;
  mlstatusreason: string;
  mlordertype: string;
  mlcreator: string;
  mlcreatorid: number;
  mlcreated: Date;
  mlorder: string;
  mlorderid: number;
  mlordered: Date;
  mlcancel: string;
  mlcancelid: number;
  mlcancelled: Date;
  mldroploc: string;
  mldropwhid: number;
  mldropeta: Date;
  mlreceive: string;
  mlreceived: Date;
  mlproduction: Date;
  mlrstatus: string;
  mlrnotes: string;
  mlrproblem: string;
  mlcalltosched: string;
  mlrpic: number;
  mlassign: string;
  mlassigndts: Date;
  mlassignid: number;
  mlassignby: string;
  mlassignbyid: number;
  mlfix: string;
  mlfixid: number;
  mlfixed: Date;
  mlnotes: string;
  mlintnotes: string;
  mlorderdelivfee: number;
  mlordertot: number;
  mlcredit: number;
  mlkey: string;
  mlacl: string;
  mlseen: Date;
  mlseencancel: Date;
  mlid2: string;
  mlsuid: any;
  PQ_materialsList: any;
}

interface PQ_materialsListFiles {
  mlfid: number;
  mlfmlid: number;
  mlfuid: number;
  mlfname: string;
  id: any;
  PQ_materialsListFiles: any;
}

interface PQ_materialsListIDX {
  mliid: number;
  mlimlid: number;
  mlimid: number;
  mlimiid: number;
  mliordered: number;
  mlipulled: number;
  mlireceived: number;
  mlicost: number;
  mlireturned: number;
  mliopt: string;
  PQ_materialsListIDX: any;
}

interface PQ_materialsListPhotos {
  mlpicid: number;
  mlpicmlid: number;
  mlpicfilename: string;
  mlpicext: string;
  mlpicdts: Date;
  mlpo: string;
  PQ_materialsListPhotos: any;
}

interface PQ_materialsListTemplate {
  mltid: number;
  mltntid: number;
  mltsid: number;
  mltname: string;
  mlttype: string;
  mltmap: string;
  mltmarket: string;
  mltservice: string;
  mltnotes: string;
  mltorder: number;
  mltview: string;
  PQ_materialsListTemplate: any;
}

interface PQ_materialsListTemplateIDX {
  mltiid: number;
  mltimltid: number;
  mltimid: number;
  mlticalcvarid: number;
  mltimap: string;
  mltcoverage: string;
  mltorder: number;
  mltmid: any;
  PQ_materialsListTemplateIDX: any;
}

interface PQ_materialsMFR {
  mid: number;
  mfr: string;
  PQ_materialsMFR: any;
}

interface PQ_materialsPhotos {
  mpid: number;
  mpmid: number;
  mplabel: string;
  mpfn: string;
  mlpmid: any;
  PQ_materialsPhotos: any;
}

interface PQ_materialsPricing {
  mpid: number;
  mpmiid: number;
  mpmid: number;
  mpgid: number;
  mpsku: string;
  mpcost: number;
  mpdts: Date;
  mpuid: number;
  mpactive: string;
  PQ_materialsPricing: any;
}

interface PQ_messageTemplates {
  mtid: number;
  mttype: string;
  mtname: string;
  mttrigger: string;
  mttriggertype: string;
  mtdelivery: string;
  mtsubject: string;
  mtmsg: string;
  mttags: string;
  mtactive: string;
  PQ_messageTemplatesNew: any;
  mttarget: string;
  mtsubjectemail: string;
  mtmsgemail: string;
  mtrecipemail: string;
  mtrecipemailcc: string;
  mtrecipemailbcc: string;
  mtmsgsms: string;
  mtrecipsms: string;
  mtattachments: string;
  PQ_messageTracking: any;
  mtjid: number;
  mtwoid: string;
  mtmessageid: string;
  mtuser: string;
  mtdts: Date;
  mtstatus: string;
  mtresult: string;
  PQ_messages: any;
  msgid: number;
  msguid: number;
  mailgunid: string;
  msgrecip: string;
  msgaltrecip: string;
  msgsubject: string;
  msgstatus: string;
  msgsentdts: Date;
  msgdelivdts: Date;
  PQ_newTemplates: any;
  ntid: number;
  nttype: string;
  ntmarket: string;
  ntwotype: string;
  ntcat: string;
  nttitle: string;
  ntview: string;
  ntaccess: number;
  ntdetail: string;
  ntlineitems: number;
}

interface PQ_notes {
  nid: number;
  njid: number;
  njcontid: number;
  nwoid: number;
  nuid: number;
  nicid: number;
  ncat: string;
  ndate: Date;
  nnote: string;
  PQ_order_Status: any;
  sosid: number;
  sostatus: string;
  id: any;
}

interface PQ_order_WO {
  sowid: number;
  sowo: string;
  soid: any;
  PQ_order_WO: any;
}

interface PQ_photos {
  photoid: number;
  pjobid: number;
  pwoid: number;
  pwotype: string;
  puser: string;
  photoname: number;
  photoext: string;
  photodts: Date;
  photolabel: string;
  phototags: string;
  photoorder: number;
  photoidcc: number;
  photodtscc: number;
  photoreq: string;
  photonotes: string;
  PQ_photosChecklist: any;
  pcid: number;
  pcwotype: string;
  pcwowtypes: string;
  pcname: string;
  pcdata: string;
  PQ_photosChecklistIDX: any;
  pciid: number;
  pcipcid: number;
  pciwoid: number;
  pcireq: number;
  PQ_photosIDX: any;
  pidxid: number;
  pidxjobid: number;
  pidxphotoid: number;
  pidxptype: string;
  pidxorder: number;
  PQ_prodServe: any;
  psid: number;
  pstype: string;
  psmarket: string;
  pscat: string;
  pstitle: string;
  psdesc: string;
  psqty: number;
  psqtytype: string;
  pstemplate: string;
  pscost: number;
  psview: string;
}

interface PQ_prodServeTemplate {
  pqtid: number;
  pqttype: string;
  pqttemplate: string;
  pqtpsid: number;
  pqtorder: number;
  pqpsid: any;
  PQ_prodServeTemplate: any;
}

interface PQ_quote {
  qid: number;
  qcid: number;
  qjid: number;
  qjrid: number;
  quid: number;
  qdate: Date;
  qsent: Date;
  qopen: Date;
  qaccept: Date;
  qstatus: string;
  qtype: string;
  qtotal: number;
  qkey: string;
  qreason: string;
  qcommuid: number;
  qcommtot: number;
  qcommdts: Date;
  qcommtot2: number;
  qcommdts2: Date;
  qqbid: number;
  qqbstat: number;
  qqbqoicenum: string;
  qqbresp: string;
  qqbitem: string;
  PQ_quoteCalculator: any;
  qcjid: number;
  qccosts: number;
  qcmarkup: number;
  qcdata: string;
  PQ_quoteWorksheetsData: any;
  wsdid: number;
  wsdwsid: number;
  wsdjid: number;
  wsdlid: number;
  wsdjservice: string;
  wsdlservice: string;
  wsdform: string;
  wsdnotes: string;
  PQ_reportUser: any;
  ruid: number;
  rurid: number;
  ruuid: number;
}

interface PQ_reports {
  rid: number;
  rname: string;
  rdesc: string;
  raccess: string;
  rdealer: string;
  rstatus: string;
  rcat: string;
  rfilephp: string;
  PQ_reports: any;
}

interface PQ_reportsAuto {
  raid: number;
  raname: string;
  rafile: string;
  raactive: string;
  rarecipients: string;
  PQ_roleDefaultPage: any;
  rdpid: number;
  rdprole: string;
  rdpgojs: string;
}

interface PQ_salesStats {
  ssid: number;
  ssuid: number;
  ssmonth: number;
  ssyear: number;
  sstotal: number;
  ssgoal: number;
  PQ_signatures: any;
  sjid: number;
  sdts: Date;
  sname: string;
  sip: string;
  sipxfrom: string;
  slatlon: string;
  sua: string;
  internal: number;
  PQ_smsTemplates: any;
  smsid: number;
  smsname: string;
  smsmsg: string;
  smsplacement: string;
  smsactive: string;
  PQ_source: any;
  sid: number;
  source: string;
}

interface PQ_supplementals {
  suid: number;
  suicid: number;
  suuid: number;
  suamountreq: number;
  suamountapp: number;
  sustatus: string;
  sudatereq: Date;
  sudate: Date;
  sunotes: string;
  PQ_suppliers: any;
  sugid: number;
  suname: string;
  suaddress1: string;
  suaddress2: string;
  sucity: string;
  sustate: string;
  suzip: string;
  sucontact: string;
  suphone: number;
  suemail: string;
  sualtemail: string;
  suadded: Date;
  suactive: string;
  suaccnum: string;
  suinventory: string;
  sulatlon: string;
  sudelivfee: number;
  susalestax: number;
  sgid: any;
}

interface PQ_suppliersGroups {
  gid: number;
  gname: string;
  gcode: string;
  gnotes: string;
  gview: string;
  gsalesrep: string;
  gsalesrepphone: string;
  gsalesrepemail: string;
  gconpricing: string;
  gconexp: Date;
  gaccnum: string;
  ginventory: string;
  PQ_suppliersGroups: any;
}

interface PQ_taskNotes {
  tnid: number;
  tntid: number;
  tnuid: number;
  tndate: Date;
  tnnote: string;
  nid: any;
  PQ_tasks: any;
  tid: number;
  tjid: number;
  twoid: string;
  tuid: number;
  tassuid: number;
  ticid: number;
  tdts: Date;
  tdeadlinedts: Date;
  tdeadlinetime: any;
  topeneddts: Date;
  tcompdts: Date;
  tcat: string;
  tstatus: string;
  tpriority: string;
  tsummary: string;
  tdetails: string;
  treason: string;
  PQ_templ: any;
  tname: string;
  ttext: string;
}

interface PQ_templates {
  tid: number;
  ttype: number;
  tname: string;
  tview: string;
  PQ_templates: any;
}

interface PQ_tracker {
  tid: number;
  tvid: number;
  tcid: number;
  tuid: number;
  tdts: Date;
  taction: string;
  tprice: number;
  tvalue: number;
  tdetail: string;
  PQ_trainingPhotos: any;
  jrtid: number;
  jrtjid: number;
  jrtdts: Date;
  jrtcategory: string;
  jrtorder: number;
  jrtlabel: string;
  jrtdetail: string;
  jrtfilename: string;
  jrtinstaller: string;
  jrpjid: any;
}

interface PQ_user {
  uid: number;
  ulogin: string;
  upass: string;
  ufirstn: string;
  ulastn: string;
  uemail: string;
  uphone: number;
  uphonemobile: number;
  uadddts: Date;
  uaddid: number;
  ueditdts: Date;
  ueditid: number;
  ulastlogin: Date;
  ulastdts: Date;
  ulastpassdts: Date;
  urole: string;
  uestimate: string;
  uclients: string;
  ujobs: string;
  uinstaller: string;
  utemplates: string;
  usuper: string;
  ustatus: string;
  uexpire: number;
  utitl: string;
  usys: string;
  ulock: string;
  umenuoverride: string;
  ucid: number;
  uaddpart: string;
  uaddpartrate: string;
  udefLot: string;
  ucntE: string;
  ucolor: string;
  ukey: string;
  uperms: string;
  ustart: string;
  ustartmobile: string;
  ufieldRe: string;
  uroles: string;
  urolesBKUP: string;
  uassign: string;
  uwidgets: string;
  urate: number;
  ulang: string;
  uintegrationcc: string;
  ucompanies: string;
  uservices: string;
  usalesgoal: number;
  usalesgoaly: number;
  ustagingaccess: number;
  umasteraccess: number;
}

interface PQ_warehouses {
  whid: number;
  whname: string;
  whaddress1: string;
  whaddress2: string;
  whcity: string;
  whstate: string;
  whzip: string;
  whcontact: string;
  whphone: number;
  whemail: string;
  whuid: number;
  whadded: Date;
  whactive: string;
  whnotes: string;
  PQ_warehousesINV: any;
  whiid: number;
  whiwhid: number;
  whimid: number;
  whimiid: number;
  whionhand: number;
  whicost: number;
  PQ_warranty: any;
  wid: number;
  wtitle: any;
  wlterm: number;
  wmterm: number;
  wdesc: string;
  wview: string;
}

interface PQ_woCheckins {
  chid: number;
  chjid: number;
  chwoid: number;
  chuid: number;
  chdate: Date;
  chdatein: Date;
  chdateout: Date;
  chcrewuids: string;
  PQ_woRoof: any;
  wojid: number;
  wonotes: string;
  wostatus: string;
}

interface PQ_workOrderInspect {
  woiid: number;
  woijid: number;
  woiwoid: number;
  woiuid: number;
  woiassignor: number;
  woiassigndate: Date;
  woiinspdate: Date;
  woieta: Date;
  woiresdate: Date;
  woiresnote: string;
  woicbnote: string;
  woistatus: string;
  woicsosig: string;
  woicsosigdts: Date;
  woicsosenddts: Date;
  woicsoip: string;
  woicsolatlon: string;
  woicsokey: string;
  PQ_workOrderInspectPhotos: any;
  woipicid: number;
  woipicwoid: number;
  woipicfilename: string;
  woipicext: string;
  woipicdts: Date;
  woipo: string;
  woDBSUPERIORROOpicwoid: any;
  PQ_workOrders: any;
  woid: number;
  wojid: number;
  wotype: string;
  woinstaller: number;
  woassignor: number;
  wowtype: string;
  wostatus: string;
  wostatususer: string;
  wostatusdate: Date;
  wostatusreason: string;
  woeta: Date;
  wostart: Date;
  wofinish: Date;
  wofinishdts: Date;
  wofinishdesc: string;
  wodeldts: Date;
  wopermit: Date;
  wopermitnum: string;
  wopermitreq: string;
  woinspection: Date;
  woinspectionlabel: string;
  woinspection2: Date;
  woinspection2label: string;
  woinspectreq: string;
  wodumpsterdate: Date;
  wodumpsterco: string;
  wonotes: string;
  woinstallernotes: string;
  worate: string;
  woratenotes: string;
  woinsp: string;
  woinspassignor: number;
  woinspassigndate: Date;
  woinspuid: number;
  woinspprob: string;
  woinspdesc: string;
  woinspdate: Date;
  woview: number;
  wokey: string;
  wocsosig: string;
  wocsosigdts: Date;
  wocsosenddts: Date;
  wocsoip: string;
  wocsolatlon: string;
  wocsokey: string;
  PQ_workOrdersAccounting: any;
  woaid: number;
  woawoid: number;
  woasupid: number;
  woasubid: number;
  woatype: string;
  woacat: string;
  woaref: string;
  woatotal: number;
  woadate: Date;
  PQ_workOrdersFiles: any;
  wofid: number;
  wofwoid: number;
  wofsupid: number;
  wofsubid: number;
  wofdesc: string;
  wofuid: number;
  woftype: string;
  wofname: string;
  woffile: string;
  wofdate: Date;
  PQ_workOrdersWorksheets: any;
  wsid: number;
  wswotype: string;
  wsform: string;
}

interface PQ_workOrdersWorksheetsData {
  wsdid: number;
  wsdwsid: number;
  wsdwoid: number;
  wsdform: string;
  wsdformBKUP: string;
  api_auth: any;
  authid: number;
  authuser: string;
  authsecret: string;
  authtoken: string;
  authtokenexpire: Date;
  authip: string;
  api_example: any;
  exampleid: number;
  exampledate: Date;
  exampledata: string;
  iMP_co: any;
  id: number;
  defirate: number;
  qbat: string;
  qbrt: string;
  qbrid: string;
  qbtokendts: Date;
  rateA: number;
  rateC: number;
  rateE: number;
  hdrinvA: string;
  hdrinvB: string;
  prodemail: string;
  salesgoal: number;
  salesgoaly: number;
  csalesgoal: number;
  csalesgoaly: number;
  reviewlink: string;
  settings_account: string;
  settings_payments: string;
  settings_roles: string;
}

interface PQ_calculator {
  caid: number;
  caname: string | null;
  shinglecostbundle: number | null;
  underlaymentcostbundle: number | null;
  icewatercost: number | null;
  hipridgecost: number | null;
  startershinglecost: number | null;
  nailcost: number | null;
  staplecost: number | null;
  ventingcost: number | null;
  caactive: string | null;
}

interface PQ_client {
  cid: number;
  cuid: number | null;
  cadate: Date | null;
  cedate: Date | null;
  ctype: string | null;
  cstatus: string | null;
  clientstatus: string | null;
  clientsubstatus: string | null;
  cismgmt: string | null;
  ccomp: string | null;
  caddr1: string | null;
  caddr2: string | null;
  ccity: string | null;
  cst: string | null;
  czip: number | null;
  cphone: number | null;
  cphonebilling: number | null;
  caltphone: number | null;
  csmsphone: number | null;
  cext: string | null;
  cfax: number | null;
  ccontact: string | null;
  ctitle: string | null;
  cemail: string | null;
  cemailAlt: string | null;
  cemailAlt2: string | null;
  cemailAlt3: string | null;
  cemailAlt4: string | null;
  cemailAlt5: string | null;
  cemailAlt6: string | null;
  ccontact2: string | null;
  ctitle2: string | null;
  cphone2: number | null;
  cext2: string | null;
  cemail2: string | null;
  cemail2cc: string | null;
  cemailbilling: string | null;
  caltemailbilling: string | null;
  curl: string | null;
  cnotes: string | null; // Text is mapped to string in TypeScript
  cpayterms: string | null;
  cview: string | null;
  csalesid: number | null;
  creferral: string | null;
  cwon: Date | null;
  clost: Date | null;
  cqbid: number | null;
  cqbresp: string | null; // Text is mapped to string in TypeScript
  clatefee: number | null;
  cwaivelate: string | null;
  clotid: number | null;
  cinid: number | null;
  capp: number | null; // TINYINT is typically represented as number in TypeScript
  cinvpays: string | null;
  cstatus2: string | null;
  cstatusuid: number | null;
  cstatusreason: string | null; // Text is mapped to string in TypeScript
  cstatusdate: Date | null;
  clatlon: string | null;
  cnnote: string | null; // Text is mapped to string in TypeScript
  cinspection: Date | null;
  clastcontact: Date | null;
  clastcontactuid: number | null;
}

interface PQ_clientNotes {
  cnid: number;
  cncid: number | null;
  cnuid: number | null;
  cndate: Date | null;
  cnnote: string | null; // TEXT is mapped to string in TypeScript
}

interface PQ_clientQB {
  Id: number | null;
  company: string | null; // 'company name'
  fullname: string | null; // 'full name'
  matched: string | null;
}

interface PQ_clientStatement {
  csid: number;
  cscid: number;
  csuid: number;
  cskey: string;
  csdtsemail: Date | null;
  csdtsview: Date | null;
}

interface PQ_client_backup {
  cid: number;
  cadate: Date | null;
  cedate: Date | null;
  ctype: string | null;
  cstatus: string | null;
  cismgmt: string | null;
  ccomp: string | null;
  caddr1: string | null;
  caddr2: string | null;
  ccity: string | null;
  cst: string | null;
  czip: number | null;
  cphone: number | null;
  cphonebilling: number | null;
  caltphone: number | null;
  cext: string | null;
  cfax: number | null;
  ccontact: string | null;
  ctitle: string | null;
  cemail: string | null;
  cemailAlt: string | null;
  cemailAlt2: string | null;
  cemailAlt3: string | null;
  cemailAlt4: string | null;
  cemailAlt5: string | null;
  cemailAlt6: string | null;
  cemailbilling: string | null;
  curl: string | null;
  cnotes: string | null; // TINYTEXT is mapped to string in TypeScript
  cpayterms: string | null;
  cview: string | null;
  csalesid: number | null;
  creferral: string | null;
  cwon: Date | null;
  clost: Date | null;
  cqbid: number | null;
}

interface PQ_co {
  coid: number;
  coapplyto: string | null;
  coname: string | null;
  colicense1: string | null;
  colicense2: string | null;
  colicense3: string | null;
  colicense4: string | null;
  coaddr1: string | null;
  coaddr2: string | null;
  cocity: string | null;
  costate: string | null;
  cozip: string | null;
  cophone1: string | null;
  cophone2: string | null;
  coemail: string | null;
  cofax: string | null;
  courl: string | null;
  cstatus: string | null;
  cstatusmaster: string | null;
  cservices: string | null; // TEXT is mapped to string
  csector: string | null;
  coins: string | null;
  comatloc: number | null;
  colatlon: string | null;
  cologo: string | null;
  coresdue: number | null;
  cocomdue: number | null;
  colaterate: number | null;
  coinnotecom: string | null; // TEXT is mapped to string
  coinnoteres: string | null; // TEXT is mapped to string
  cointerms: string | null; // TEXT is mapped to string
  coincontingency: string | null; // TEXT is mapped to string
  coeula: string | null; // TEXT is mapped to string
  coeulaversion: number | null;
  cocctoken: string | null;
  coreviewlink: string | null;
  coreviewtext: string | null;
  coexpdaysres: number | null;
  coexpdayscom: number | null;
  cotimezone: string | null;
  cocheckout: string | null;
}

interface PQ_contingency {
  ctid: number;
  ctlid: number | null;
  ctcid: number | null;
  ctinid: number | null;
  ctjid: number | null;
  ctstatus: number | null;
  ctdts: Date | null;
  ctname: string | null;
  ctip: string | null;
  ctipxfrom: string | null;
  ctlatlon: string | null;
  ctua: string | null;
}

interface PQ_crewRates {
  crid: number;
  cruid: number | null;
  crwotype: string | null;
  crdata: string | null;
}

interface PQ_crm {
  crmid: number;
  crmname: string | null;
  crmaddr1: string | null;
  crmaddr2: string | null;
  crmcity: string | null;
  crmstate: string | null;
  crmzip: string | null;
  crmemail: string | null;
  crmphone: string | null;
  crmphonealt: string | null;
  crmweb: string | null;
  crmactive: string | null;
  crmtags: string | null;
  crmcat: string | null;
}

interface PQ_crmNames {
  crmnid: number;
  crmncrmid: number | null;
  crmnname: string | null;
  crmnemail: string | null;
  crmnphone: string | null;
}

interface PQ_deficiency {
  dfid: number;
  dfcat: string | null;
  dfname: string | null;
  dfdesc: string | null;
  dfcorrect: string | null;
  dfunit: string | null;
  dfcost: number | null;
}

interface PQ_emailTriggers {
  eid: number;
  elabel: string | null;
  erecip: string | null;
}

interface PQ_events {
  eid: number;
  euid: number | null;
  ejid: number | null;
  ecid: number | null;
  elid: number | null;
  elocid: number | null;
  etype: string | null;
  estartdts: Date | null;
  eenddts: Date | null;
  eallday: string | null;
  etitle: string | null;
  edesc: string | null;
  estatus: string | null;
  eauid: number | null;
  eadts: Date | null;
  eduration: number | null;
  edurationtyp: string | null;
  notify_emails: string | null;
  notify_names: string | null;
}

interface PQ_invoiceNote {
  inid: number;
  innote: string;
}

interface PQ_invoicePaymentsDeclines {
  ipdid: number;
  ipdinvid: number | null;
  ipddts: Date | null;
  ipdpayload: string | null;
  ipdresult: string | null;
}

interface PQ_invoicePaymentsPending {
  ipid: number;
  ipcid: number | null;
  ipjid: number | null;
  ipjrid: number | null;
  ipuid: number | null;
  ipdate: Date | null;
  ipamt: number | null;
  ipfee: number | null;
  iptype: string | null;
  ipmeth: string | null;
  ipchknum: string | null;
  ipqbid: string | null;
  ipqbresp: string | null;
  ipccpayload: string | null;
  ipccresponse: string | null;
}

interface PQ_job {
  jid: number;
  jcontid: number | null;
  jcid: number | null;
  jlid: number | null;
  jbid: number | null;
  juid: number | null;
  jouid: number | null;
  jauid: number | null;
  jpmgr: number | null;
  jadate: Date | null;
  jstatus: string | null;
  qstatus: string | null;
  jsched: Date | null;
  jtype: string | null;
  jsector: string | null;
  jwork: string | null;
  jprefdate: Date | null;
  jodeldts: Date | null;
  jodumpsterco: string | null;
  jodumpsterdate: Date | null;
  jopermit: Date | null;
  joinspection: Date | null;
  jinstaller: number | null;
  jinstallon: Date | null;
  jinstalldate: Date | null;
  jinstalldesc: string | null;
  jinsurance: string | null;
  jinsuranceco: string | null;
  jinsuranceadj: string | null;
  jinsuranceadjphone: number | null;
  jinsuranceadjemail: string | null;
  jpublicadj: number | null;
  jorigcoverage: number | null;
  jclaimnum: string | null;
  jwarranty: string | null;
  jservice: string | null;
  jnotes: string | null;
  jreason: string | null;
  jreasonuid: number | null;
  jreasondts: Date | null;
  jlink: number | null;
  jcopiedfrom: number | null;
  jmailed: number | null;
  jstarted: Date | null;
  jfinished: Date | null;
  jeta: Date | null;
  jsubmitted: Date | null;
  jkey: string | null;
  jrate: string | null;
  jratenotes: string | null;
  jcontact: string | null;
  jcontactphone: number | null;
  jwoct: number | null;
  jlotid: number | null;
  jqnotes: string | null;
}

interface PQ_jobCost {
  jcostid: number;
  jcjid: number;
  jcjrid: number | null;
  jcuid: number | null;
  jcdts: Date | null;
  jcmatordered: number | null;
  jcshopmat: number | null;
  jcdisposal: number | null;
  jcmiscmater: number | null;
  jcpermit: number | null;
  jceagleview: number | null;
  jcsublabor: number | null;
  jcexpense: number | null;
  jcextras: number | null;
  jctotalcost: number | null;
  jcreturns: number | null;
  jcmarketing: number | null;
  jcleadfee: number | null;
  jcfinalcost: number | null;
  jcnotes: string | null;
  jcmisc: number | null;
  jcdone: number | null;
  jcwarrcost: number | null;
  jccommpayout: number | null;
}

interface PQ_leads {
  lid: number;
  luid: number | null;
  lcid: number | null;
  ladate: Date | null;
  lstatus: string | null;
  lstatus2: string | null;
  ltype: string | null;
  lservice: string | null;
  lstatusuid: number | null;
  lstatusreason: string | null;
  lstatusdate: Date | null;
  llastcontact: Date | null;
  llastcontactuid: number | null;
  lsource: string | null;
  lcomp: string | null;
  lcontact: string | null;
  ltitle: string | null;
  llname: string | null;
  laddr1: string | null;
  laddr2: string | null;
  lcity: string | null;
  lst: string | null;
  lzip: number | null;
  llatlon: string | null;
  lphone: string | null;
  lext: string | null;
  laltphone: string | null;
  laltext: string | null;
  lemail: string | null;
  llotid: number | null;
  lnotes: string | null;
  lfax: string | null;
  lcontact2: string | null;
  ltitle2: string | null;
  lphone2: number | null;
  lext2: string | null;
  lemail2: string | null;
  lemail2cc: string | null;
  lbtype: string | null;
  lbfloors: number | null;
  lbroofmat: string | null;
  lbhatch: string | null;
  lbheight: number | null;
  linspection: Date | null;
  linspectioncomp: Date | null;
  linspectionnotes: string | null;
  llocnotes: string | null;
  lapp: number | null;
  linvpays: string | null;
  linsuranceco: string | null;
  lclaimnum: string | null;
  lsimpleinspections: string | null;
}

interface PQ_leadsNotes {
  lnid: number;
  lnlid: number | null;
  lncid: number | null;
  lnuid: number | null;
  lncat: string | null;
  lndate: Date | null;
  lnfollowup: Date | null;
  lnfollowedup: number | null;
  lnnote: string | null;
}

interface PQ_location {
  lid: number;
  ladate: Date | null;
  ledate: Date | null;
  lclient: number | null;
  lpid: number | null;
  lname: string | null;
  laddr1: string | null;
  laddr2: string | null;
  lcity: string | null;
  lst: string | null;
  lzip: number | null;
  lcounty: string | null;
  llatlon: string | null;
  lphone: number | null;
  lext: string | null;
  lcontact: string | null;
  lnotes: string | null;
  lview: string | null;
}

interface PQ_log {
  logid: number;
  logcat: string | null;
  logtitle: string | null;
  loguid: number | null;
  logdts: Date | null;
  logdataid: number | null;
  logaltdataid: number | null;
  lognote: string | null;
}

interface PQ_login {
  lid: number;
  luid: number | null;
  ldts: Date | null;
  luname: string | null;
  lremote_addr: string | null;
  lforward_for: string | null;
}

interface PQ_lot {
  lotid: number;
  lotname: string | null;
  lotaddress1: string | null;
  lotaddress2: string | null;
  lotcity: string | null;
  lotstate: string | null;
  lotzip: string | null;
  lotphone: number | null;
  lotemail: string | null;
  lotlogo: string | null;
  lothdr: string | null;
  lotview: string | null;
  lotcctoken: string | null;
}

interface PQ_materials {
  mid: number;
  mtype: string | null;
  mmarket: string | null;
  mcat: string | null;
  mtitle: string | null;
  mdesc: string | null;
  mqty: number | null;
  mqtytype: string | null;
  mtemplate: string | null;
  mcost: number | null;
  mservice: string | null;
  mview: string | null;
}

interface PQ_messageTemplatesNew {
  mtid: number;
  mttype: string;
  mtname: string | null;
  mttrigger: string | null;
  mttarget: string | null;
  mttriggertype: string | null;
  mtdelivery: string | null;
  mtsubjectemail: string | null;
  mtmsgemail: string | null;
  mtrecipemail: string | null;
  mtrecipemailcc: string | null;
  mtrecipemailbcc: string | null;
  mtmsgsms: string | null;
  mtrecipsms: string | null;
  mttags: string | null;
  mtactive: string | null;
  mtattachments: string | null;
}

interface PQ_messageTracking {
  mtid: number;
  mtjid: number | null;
  mtwoid: string | null;
  mttype: string | null;
  mtmessageid: string | null;
  mtuser: string | null;
  mtdts: Date | null;
  mtstatus: string | null;
  mtresult: string | null;
}

interface PQ_messages {
  msgid: number;
  msguid: number | null;
  mailgunid: string | null;
  msgrecip: string | null;
  msgaltrecip: string | null;
  msgsubject: string | null;
  msgstatus: string | null;
  msgsentdts: Date | null;
  msgdelivdts: Date | null;
}

interface PQ_newTemplates {
  ntid: number;
  nttype: string | null;
  ntmarket: string | null;
  ntwotype: string | null;
  ntcat: string | null;
  nttitle: string | null;
  ntview: string | null;
  ntaccess: number | null;
  ntdetail: string | null;
  ntlineitems: number | null;
}

interface PQ_order_Status {
  sosid: number;
  sostatus: string | null;
}

interface PQ_photosChecklist {
  pcid: number;
  pcwotype: string | null;
  pcwowtypes: string | null;
  pcname: string | null;
  pcdata: string | null;
}
